/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pkginterface_InterfaceJavaC */

#ifndef _Included_pkginterface_InterfaceJavaC
#define _Included_pkginterface_InterfaceJavaC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pkginterface_InterfaceJavaC
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pkginterface_InterfaceJavaC_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     pkginterface_InterfaceJavaC
 * Method:    createDeck
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_pkginterface_InterfaceJavaC_createDeck
  (JNIEnv *, jobject, jint);

/*
 * Class:     pkginterface_InterfaceJavaC
 * Method:    deleteDeck
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_pkginterface_InterfaceJavaC_deleteDeck
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
