/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class version2_InterfaceJavaC */

#ifndef _Included_version2_InterfaceJavaC
#define _Included_version2_InterfaceJavaC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     version2_InterfaceJavaC
 * Method:    createDeck
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_version2_InterfaceJavaC_createDeck
  (JNIEnv *, jclass, jint);

/*
 * Class:     version2_InterfaceJavaC
 * Method:    deleteDeck
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_version2_InterfaceJavaC_deleteDeck
  (JNIEnv *, jclass);

/*
 * Class:     version2_InterfaceJavaC
 * Method:    getVerticeColor
 * Signature: (II)C
 */
JNIEXPORT jchar JNICALL Java_version2_InterfaceJavaC_getVerticeColor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     version2_InterfaceJavaC
 * Method:    modifyVertice
 * Signature: (CII)V
 */
JNIEXPORT void JNICALL Java_version2_InterfaceJavaC_modifyVertice
  (JNIEnv *, jclass, jchar, jint, jint);

/*
 * Class:     version2_InterfaceJavaC
 * Method:    isModifyVertice
 * Signature: (CII)I
 */
JNIEXPORT jint JNICALL Java_version2_InterfaceJavaC_isModifyVertice
  (JNIEnv *, jclass, jchar, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
